# Generated by Django 4.1 on 2024-07-09 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non binary'), ('O', 'Other')], default='O', max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('post_title', models.CharField(max_length=400)),
                ('post_body', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CRUDAPP.userprofile')),
            ],
        ),
    ]
