# Generated by Django 4.1 on 2024-07-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='UserCredentials',
        ),
    ]
