# Generated by Django 4.1 on 2024-07-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0005_userbio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbio',
            name='about',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
